### ISSUE TITLE
Simulink connection setup in config.yaml file

### ISSUE THREAD

**Issue by cjffly** [ORNL-Real-Sim/FIXS#20]
In the config yaml file, there are following statement for simulink setup:
```
CarMakerSetup:
    # whether or not enable CarMaker (default: false)
    EnableCosimulation: true
    
    # if true, ego state is sent from Simulink.
    # if false, ego state is sent from User.cpp 
    EnableEgoSimulink: false
```
I am not sure if this `EnableEgoSimulink: false` is functioning properly or not? @yunlishao it seems even with `false` setting, we are still able to run with  Simlink.
